### PR TITLE
enhance the performance of the database on heavy data queries

### PR DESCRIPTION
**Pull request by Mhamad-Raad**
# Performance
## In this project we have done the followings:
- Added indexes for the database.

this action has been done for the database to have better performance when querying large data, and the difference is demonstrated in the following pictures.

### Done 💯 🎉

### CODE REVIEW

**Review by vickymarz — CHANGES_REQUESTED** [review]
Hi @Mhamad-Raad, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## ❌ Invalid Code Review Request

You have submitted a project, that does not use the new microverse provided readme template. Kindly update your readme to use the new microverse[ readme ](https://github.com/microverseinc/readme-template)and make sure you edit all the sections to fit your project. Please note that all sections are compulsory except FAQ

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Mhamad-Raad** [comment]
@vickymarz  hey there, can you please tell me what is not there?

**Comment by Mhamad-Raad** [comment]
please keep in mind that the updated version of readme file is already in main

**Review by thecodechaser — APPROVED** [review]
## STATUS: APPROVED 🟢

## Hi @Mhamad-Raad👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 🎉
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
